added picom and lightdm theme

diff --git a/berserk-config-xfce/berserk-config-xfce.install b/berserk-config-xfce/berserk-config-xfce.install
--- a/berserk-config-xfce/berserk-config-xfce.install
+++ b/berserk-config-xfce/berserk-config-xfce.install
@@ -1,4 +1,28 @@
+## Colors ----------------------------
+
+# Text Reset
+Color_Off='\033[0m'
+
+# Regular Colors
+Black='\033[0;30m' Red='\033[0;31m' Green='\033[0;32m' Yellow='\033[0;33m'
+Blue='\033[0;34m' Purple='\033[0;35m' Cyan='\033[0;36m' White='\033[0;37m'
+
+## -----------------------------------
+
+change_theme() {
+  echo -e ${Blue}"\n[*] Applying ${Purple}${1}${Blue} theme for LightDM..."${Color_Off}
+  sed -i -e "s|background =.*|background = $1|g" /etc/lightdm/lightdm-gtk-greeter.conf.new
+  sed -i -e "s|theme-name =.*|theme-name = $2|g" /etc/lightdm/lightdm-gtk-greeter.conf.new
+  cp /etc/lightdm/lightdm-gtk-greeter.conf.new /etc/lightdm/lightdm-gtk-greeter.conf
+  if [[ "$?" == 0 ]]; then
+    echo -e ${Green}"[+] Theme applied successfully."${Color_Off}
+  else
+    echo -e ${Red}"[!] Failed to apply new theme.\n"${Color_Off}
+  fi
+}
+
 post_install() {
+  change_theme '/usr/share/backgrounds/xfce/berserkarch-1.png' 'Kali-Dark'
   echo ">>>"
   echo ">>> Berserk Arch Openbox configuration has been installed."
   echo ">>>"
